-- Even Fibonacci Numbers
-- Problem 2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be : 
-- 1, 2, 3, 5, 8, 13, 21, 34 ,55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

fibonacci :: Int -> Int -> [Int]
fibonacci a b = [a + b] ++ (fibonacci b (a + b))

sumEvenFibonacci :: Int -> Int
sumEvenFibonacci number = sum (filter even (take number (fibonacci 0 1)))

main = do
    number <- getLine
    print $ sumEvenFibonacci (read number :: Int)

